import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// Vite + React + Tailwind v4. The Tailwind v4 plugin replaces the old
// postcss + @tailwindcss/postcss combo — it reads the @theme directive
// from src/index.css (which was generated by the Super Design skill)
// and emits the utility layer on demand.
export default defineConfig({
  plugins: [react(), tailwindcss()],
});
