import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// Vite + React + Tailwind v4. The Tailwind v4 plugin replaces the old
// postcss + @tailwindcss/postcss combo — it reads the @theme directive
// from src/index.css (which was generated by the Super Design skill)
// and emits the utility layer on demand.
//
// Base path: local dev defaults to '/'. Production builds (GitHub Pages
// deployment under https://eldergenix.github.io/SUPER-DESIGN/) set
// VITE_BASE_PATH=/SUPER-DESIGN/ in the Actions workflow so that hashed
// asset URLs in the built HTML resolve under the project subpath. Forks
// can override this env var without editing the config.
export default defineConfig({
  base: process.env.VITE_BASE_PATH ?? '/',
  plugins: [react(), tailwindcss()],
});
